# Site settings
title: 〰️ jennifer tran
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  software engineer / writer / illustrator
baseurl:  # the subpath ofyour site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  botanical

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio: 
    output: false
    permalink: /portfolio/:path/
  poetry:
    output: false
    permalink: /poetry/:path/


